# Generated by Django 3.0.7 on 2020-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Corretor', max_length=100)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.IntegerField()),
                ('end', models.CharField(max_length=500)),
            ],
        ),
    ]
