# Generated by Django 3.0.7 on 2020-07-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreendimento', models.CharField(help_text='Nome do empreendimento', max_length=100)),
                ('cidade', models.CharField(help_text='Cidade', max_length=100)),
                ('estado', models.CharField(help_text='Estado', max_length=100)),
                ('bairro', models.CharField(help_text='Bairro', max_length=100)),
                ('rua', models.CharField(max_length=500)),
                ('numero', models.IntegerField()),
                ('tipologia', models.CharField(help_text='Tipologia', max_length=500)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(help_text='Nome do Corretor', max_length=200),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=200)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.IntegerField()),
                ('end', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Corretores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('corretores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Corretor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
        ),
    ]
