# Generated by Django 3.0.7 on 2020-07-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200722_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
